### ISSUE TITLE
manifest.json No such file or directory

### ISSUE THREAD

**Issue by tahiriqbalnajam** [trumanwong/laravel-vue-admin#2]
Hi,
Thanks for such a brilliant effort,
After installation and run "npm run watch"
I am getting this issue on browser "file_get_contents(public\build/manifest.json): Failed to open stream: No such file or directory"

Is there something I am missing while installing.

**Comment by trumanwong** [comment]
Now you pull the code again, due to the element-plus upgrade, the path of the i18n code has changed, so your compilation failed.

**Comment by tahiriqbalnajam** [comment]
Working fine now,
Thank you
