### ISSUE TITLE
Vue Devtools not working

### ISSUE THREAD

**Issue by tahiriqbalnajam** [trumanwong/laravel-vue-admin#3]
Hi,
Thanks for such a nice things, and I have developed a lot on this.
One issue which I am facing is "Devtools inspection is not available because it's in production mode or explicitly disabled by the author."
Kindly guide where I can activate Devtools

**Comment by trumanwong** [comment]
please show detail

**Comment by tahiriqbalnajam** [comment]
![image](https://github.com/trumanwong/laravel-vue-admin/assets/2802893/672623b6-86d9-4652-bca1-582c0ef372dd)
![image](https://github.com/trumanwong/laravel-vue-admin/assets/2802893/33e90526-375f-411b-9f61-42d2fd95f9af)

In above pictures you can see that devTool is detecting the vuejs but putting error that it is in production mode, although I am running it on my local machine with "npm run watch"

**Comment by trumanwong** [comment]
I haven't used this plugin, I hope this link is useful to you: [Vue Tip: Force-Enable Vue Devtools in Production Build
](https://mokkapps.de/vue-tips/force-enable-vue-devtools-in-production-build/)
